# Generated by Django 4.1 on 2022-10-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_imagen_delete_entregable_delete_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='receta',
            name='texto',
            field=models.CharField(max_length=5000),
        ),
    ]
