# Generated by Django 4.1 on 2022-10-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocinero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cocineros'),
        ),
    ]
