# Generated by Django 4.1 on 2022-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_remove_comentario_nombreyapellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
