# Generated by Django 4.1 on 2022-10-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_comentario_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='Comentario',
        ),
    ]
