# Generated by Django 4.1 on 2022-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_rename_texto_comentario_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta_Amateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ingrediente', models.CharField(blank=True, max_length=5000, null=True)),
                ('texto', models.CharField(max_length=5000)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
