# Generated by Django 4.1 on 2022-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_receta_amateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nivel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
